### ISSUE TITLE
org.ehcache.spi.serialization.UnsupportedTypeException: No serializer found for type LookupVolumeResult

### ISSUE THREAD

**Issue by maregeo** [lokra/seaweedfs-client#3]
`FileSource fileSource = new FileSource();
		// SeaweedFS master server host
		fileSource.setHost("192.168.100.114");
		// SeaweedFS master server portaaaaa
		fileSource.setPort(9335);
		// Startup manager and listens for the change
		try {
			fileSource.startup();
		} catch (IOException e) {
			e.printStackTrace();
		}
		FileTemplate template = new FileTemplate(fileSource.getConnection());
		File file = new File("G:\\007.JPG");
		FileHandleStatus status = template.saveFileByStream("007.jpg", new FileInputStream(file));`

that's my code get this error
**org.ehcache.spi.serialization.UnsupportedTypeException: No serializer found for type LookupVolumeResult.class
so i rewrite LookupVolumeResult to  implements  java.io.Serializable the problem sloved**

**Comment by ChihoSin** [comment]
I will try to fix this bug at next version.

**Comment by ChihoSin** [comment]
fixed #3 at version 0.7.3.RELEASE.
