### ISSUE TITLE
Documentation / Developer Guide?

### ISSUE THREAD

**Issue by sivabudh** [lokra/seaweedfs-client#4]
Hello,

I'm interested in using your library in a production system, and was wondering if there's a developer guide somewhere I couldn't find? Your library looks promising.

**Comment by ChihoSin** [comment]
@sivabudh 
Hi,

Thanks for using, if you want to using this library in a production, I think you should consider the following questions:

- [ ] [SeaweedFS](https://github.com/chrislusf/seaweedfs) is unstable library now, the author is busy with work, there have been no updated versions for a long time.
- [ ] You must be rigorously tested, especially the cache part!

Of course, welcome to contribute some code!

**Comment by sivabudh** [comment]
If not SeaweedFS, then do you have a suggestion might be a good alternative?

**Comment by ChihoSin** [comment]
SeaweedFS is the best LOSF file system what I've seen, if you seek ultimate stability, HFS is a good choice.
